numpy是Python科学计算的基础包，重在数据处理
是scipy和pandas等科学计算的基础
n维数组-》ndarray
线性运算、傅里叶变换、矩阵运算
引入numpy第三方库

In [14]:

# import numpy as np

In [4]:
#将列表转换成数组
import numpy as np
#
a = np.array([10,20,30])
a

array([10, 20, 30])

In [6]:
b = np.array(((1,2),(3,4)))
b

array([[1, 2],
       [3, 4]])

In [7]:
#了解对象的属性和方法
#dytpe:元素的数据类型
#size:元素的个数
#ndim:维度
#shape:形状-每一维有几个元素
a.ndim
a.shape

(3,)

In [10]:
#元素访问,切片操作后仍然是数组，不是列表
# a[:]
a[[0,2]]

array([10, 30])

In [11]:
#二维数组元素遍历
#层进式访问方式
c = np.array(range(1,13)).reshape(3,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

c[0,1] = c[0][1]效果相当
层进式，从外到内递进
先进入外层然后操作内层，访问量子对象

In [18]:

c[:2][:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
c[:2,:2]

array([[1, 2],
       [5, 6]])

In [29]:
#布尔索引-输出一维数组的符合结果
# c[c>6]
c[(a>3) | (a<10)]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
# np.arange(start=,stop=,step)->数据类型随机
# np.linspace(start=,stop=,num=,endpoint=) 返回开始到截止的num个等差数列
# np.zeros((row,col))
# np.ones((row,col))
# reshape

In [9]:
# 基本运算
# 广播原则->避免for循环
import numpy as np
ar = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,11,10]])
# arr = [[1,2,3,4,5],
#        [4,5,6,7,8],
#        [7,8,9,11]]
ar[1:,2:]

array([[ 6,  7,  8],
       [ 9, 11, 10]])

In [10]:
#作业
import numpy as np
n=int(input())
arr = np.arange(n,n+12)
print("数组: {}".format(arr))
print("最大值: {}".format(np.max(arr)))
print("和: {}".format(np.sum(arr)))
print("标准差: {:.2f}".format(np.std(arr)))

数组: [23 24 25 26 27 28 29 30 31 32 33 34]
最大值: 34
和: 342
标准差: 3.45


pandas数据分析中最重要的第三方库
pandas的主要功能：数据结构、数据访问、数据读写、数据处理、数据分析、数据可视化


In [ ]:
import pandas as pd

数据结构：
Series:一维带标签的数组;类似于字典

In [11]:
data = [1,2,3,4,5]
data1 = pd.Series(data,index=[7,8,9,5,3])
data1

7    1
8    2
9    3
5    4
3    5
dtype: int64

In [13]:
s1 = pd.Series([100,200,300])
s1

0    100
1    200
2    300
dtype: int64

In [14]:
s2 = pd.Series([10,20,30,40],index=('a','b','c','d'))
s2

a    10
b    20
c    30
d    40
dtype: int64

属性:index、values、size
索引优先于行号

易错点:对Series数据结构，当索引不明确时，切片时一定要注意，切片索引是按照默认“行号”为主

In [15]:
s2['a']

10

In [ ]:
s2.drop(2)

drop是假删除，必须加上implace=True参数才可以真正删除这条数据